name: auto-format
on: [push, pull_request]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.ref_name }}
      - name: install black
        run: |
          pip install -U pip
          pip install black
      - name: format code
        run: python3 -m black .
      - name: Push changes
        run: |
          git config --global user.name 'themysticsavages'
          git config --global user.email 'themysticsavages@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "black"
          git push
